version: "3"

services:
  jdibot:
    build: ./
    restart: always
    ports:
      - 5000:5000
    links:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
    - 27017:27017
    restart: always
