package org.neustupov.javadevinterviewbot.botapi.states;

public enum  BotState {

  SHOW_START_MENU,
  SHOW_SEARCH,
  SHOW_LEVEL_MENU,
  SHOW_CATEGORY_MENU,
  SHOW_SPRING_CATEGORY_MENU,
  SHOW_CATEGORY,
  SHOW_QUESTION,
  SHOW_SEARCH_RESULT,

  FILLING_SEARCH,

  PAGINATION_PAGE
}
